In [1]:
import numpy as np

In [2]:
import scipy as sp

In [3]:
def quad(x):
    return x**3 - 2.0*x**2 + 5.0

In [4]:
res = sp.optimize.minimize(quad, 1000)

In [5]:
res.x

array([1.33333333])

In [6]:
res.fun

3.8148148148148144

In [7]:
data = np.random.normal(5, 3, 10)
data

array([ 9.24185409,  2.93381045,  4.50918401,  3.99624998,  5.11397574,
       -1.12870605,  2.41360639,  2.85009185,  2.51779024,  9.14187958])

In [8]:
data.mean()

np.float64(4.15897362719599)

In [9]:
data.std()

np.float64(2.9772424037692837)

In [10]:
x = np.array([1, 3, 2, 7, -5, -11, 5, 8, 3, -1])

In [11]:
y = sp.fftpack.fft(x)

In [12]:
y

array([ 12.         -0.j        ,  10.52786405 +5.42882455j,
       -25.5623059 -13.31479123j,  19.47213595 +4.53076859j,
        -5.4376941  -8.22899353j,   0.         -0.j        ,
        -5.4376941  +8.22899353j,  19.47213595 -4.53076859j,
       -25.5623059 +13.31479123j,  10.52786405 -5.42882455j])

In [13]:
a = np.array([[1, 6], [7, 11]])
b = np.array([14, 23])

In [14]:
sp.linalg.solve(a, b)

array([-0.51612903,  2.41935484])

In [15]:
u = np.array([1,2,3,4,5,6])
v = np.array([1,8,27,64,125,216])

In [16]:
f = sp.interpolate.interp1d(u, v)

In [17]:
f(2.5)

array(17.5)

In [18]:
mat = np.array([[0,1,0,0,0], [0,2,0,0,0], [0,0,0,0,-1], [0,0,3,0,0], [2,1,0,0,0]])

In [19]:
sparse_mat = sp.sparse.csr_matrix(mat)

In [20]:
print(sparse_mat)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 6 stored elements and shape (5, 5)>
  Coords	Values
  (0, 1)	1
  (1, 1)	2
  (2, 4)	-1
  (3, 2)	3
  (4, 0)	2
  (4, 1)	1


In [21]:
from scipy.cluster.vq import kmeans, vq

In [22]:
data = 5.0 + 3.0*np.random.rand(100,2)

In [23]:
centroids, _ = kmeans(data, 5)

In [24]:
idx, _ = vq(data, centroids)

In [25]:
print(idx)

[2 2 2 1 2 2 3 4 3 4 4 0 0 2 0 3 4 3 2 1 4 2 0 0 4 1 2 3 4 2 3 4 0 3 1 0 0
 0 0 3 1 1 0 3 2 0 2 0 1 4 0 2 0 2 0 2 0 2 0 2 2 4 4 2 3 2 2 4 1 3 0 0 1 0
 0 1 0 1 1 4 2 1 4 0 4 4 1 4 4 3 1 3 0 3 2 2 0 1 0 4]
